name: forceagri_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:        ^1.0.8
  firebase_core:          ^3.13.0
  firebase_auth:          ^5.5.3
  flutter_riverpod:       ^2.6.1
  shared_preferences:     ^2.5.3
  mobile_scanner:         ^7.0.0
  cloud_firestore:        ^5.6.7
  intl:                   ^0.20.2
  pdf:                    ^3.11.3
  printing:               ^5.14.2
  flutter_cache_manager:  ^3.4.1
  connectivity_plus:      ^6.1.4
  http:                   ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:          ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.20

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo_transparent.png   
    - assets/app_icon_transparent.png  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo_transparent.png"

flutter_native_splash:
  color: "#f9faf5"
  image: "assets/app_logo_transparent.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center